// <auto-generated />
using System;
using Ecom.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecom.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20250320084454_ConvertEnumsToIntInDb")]
    partial class ConvertEnumsToIntInDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecom.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "1",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "NEB",
                            DisplayOrder = 1,
                            Name = "NEB",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "1",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "HSEB",
                            DisplayOrder = 3,
                            Name = "HSEB",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "1",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "SLC",
                            DisplayOrder = 3,
                            Name = "SLC",
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "1",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Book",
                            DisplayOrder = 3,
                            Name = "Book",
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            CreatedBy = "1",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Exercise Book",
                            DisplayOrder = 3,
                            Name = "Exercise Book",
                            Status = true
                        },
                        new
                        {
                            Id = 6,
                            CreatedBy = "1",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Jhura Kagaj",
                            DisplayOrder = 3,
                            Name = "Jhura Kagaj",
                            Status = true
                        },
                        new
                        {
                            Id = 7,
                            CreatedBy = "1",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kawadi",
                            DisplayOrder = 3,
                            Name = "Kawadi",
                            Status = true
                        },
                        new
                        {
                            Id = 8,
                            CreatedBy = "1",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Religious",
                            DisplayOrder = 3,
                            Name = "Religious",
                            Status = true
                        },
                        new
                        {
                            Id = 9,
                            CreatedBy = "1",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Election",
                            DisplayOrder = 2,
                            Name = "Election",
                            Status = true
                        });
                });

            modelBuilder.Entity("Ecom.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("FiscalYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<bool?>("status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Class");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "One"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Two"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Three"
                        });
                });

            modelBuilder.Entity("Ecom.Models.DropdownV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Para")
                        .HasColumnType("text");

                    b.Property<int?>("ParaId")
                        .HasColumnType("integer");

                    b.Property<string>("ParaModel")
                        .HasColumnType("text");

                    b.Property<int?>("ParentParaId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DropdownV");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Para = "5",
                            ParaId = 1001,
                            ParaModel = "PerPokaSize",
                            ParentParaId = 2001,
                            Remarks = "PerPokaSize",
                            Status = true,
                            Value = "5"
                        },
                        new
                        {
                            Id = 2,
                            Para = "10",
                            ParaId = 1001,
                            ParaModel = "PerPokaSize",
                            ParentParaId = 2001,
                            Remarks = "PerPokaSize",
                            Status = true,
                            Value = "10"
                        },
                        new
                        {
                            Id = 3,
                            Para = "15",
                            ParaId = 1001,
                            ParaModel = "PerPokaSize",
                            ParentParaId = 2001,
                            Remarks = "PerPokaSize",
                            Status = true,
                            Value = "15"
                        },
                        new
                        {
                            Id = 4,
                            Para = "20",
                            ParaId = 1001,
                            ParaModel = "PerPokaSize",
                            ParentParaId = 2001,
                            Remarks = "PerPokaSize",
                            Status = true,
                            Value = "20"
                        },
                        new
                        {
                            Id = 5,
                            Para = "25",
                            ParaId = 1001,
                            ParaModel = "PerPokaSize",
                            ParentParaId = 2001,
                            Remarks = "PerPokaSize",
                            Status = true,
                            Value = "25"
                        },
                        new
                        {
                            Id = 6,
                            Para = "30",
                            ParaId = 1001,
                            ParaModel = "PerPokaSize",
                            ParentParaId = 2001,
                            Remarks = "PerPokaSize",
                            Status = true,
                            Value = "30"
                        },
                        new
                        {
                            Id = 7,
                            Para = "35",
                            ParaId = 1001,
                            ParaModel = "PerPokaSize",
                            ParentParaId = 2001,
                            Remarks = "PerPokaSize",
                            Status = true,
                            Value = "35"
                        },
                        new
                        {
                            Id = 8,
                            Para = "40",
                            ParaId = 1001,
                            ParaModel = "PerPokaSize",
                            ParentParaId = 2001,
                            Remarks = "PerPokaSize",
                            Status = true,
                            Value = "40"
                        },
                        new
                        {
                            Id = 9,
                            Para = "45",
                            ParaId = 1001,
                            ParaModel = "PerPokaSize",
                            ParentParaId = 2001,
                            Remarks = "PerPokaSize",
                            Status = true,
                            Value = "45"
                        },
                        new
                        {
                            Id = 10,
                            Para = "50",
                            ParaId = 1001,
                            ParaModel = "PerPokaSize",
                            ParentParaId = 2001,
                            Remarks = "PerPokaSize",
                            Status = true,
                            Value = "50"
                        },
                        new
                        {
                            Id = 11,
                            Para = "Male",
                            ParaId = 1002,
                            ParaModel = "Gender",
                            ParentParaId = 2002,
                            Remarks = "Gender",
                            Status = true,
                            Value = "Male"
                        },
                        new
                        {
                            Id = 12,
                            Para = "Female",
                            ParaId = 1002,
                            ParaModel = "Gender",
                            ParentParaId = 2002,
                            Remarks = "Gender",
                            Status = true,
                            Value = "Female"
                        },
                        new
                        {
                            Id = 13,
                            Para = "Others",
                            ParaId = 1002,
                            ParaModel = "Gender",
                            ParentParaId = 2002,
                            Remarks = "Gender",
                            Status = true,
                            Value = "Others"
                        });
                });

            modelBuilder.Entity("Ecom.Models.FiscalYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("FiscalYear");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "2080"
                        },
                        new
                        {
                            Id = 2,
                            Name = "2081"
                        },
                        new
                        {
                            Id = 3,
                            Name = "2082"
                        });
                });

            modelBuilder.Entity("Ecom.Models.Forma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssociatedFormaId")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Page")
                        .HasColumnType("integer");

                    b.Property<int?>("PrintAchieved")
                        .HasColumnType("integer");

                    b.Property<int?>("PrintTarget")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Forma");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TA-32",
                            Page = 32,
                            PrintTarget = 205000,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "33-40",
                            PrintTarget = 205000,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "41-51",
                            PrintTarget = 205000,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "52-62",
                            PrintTarget = 205000,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "TA-62",
                            PrintTarget = 205000,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "33-40",
                            PrintTarget = 205000,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "41-51",
                            PrintTarget = 205000,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "52-62",
                            PrintTarget = 205000,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "64-93",
                            Page = 32,
                            PrintTarget = 205000,
                            ProductId = 3
                        });
                });

            modelBuilder.Entity("Ecom.Models.JobTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Desc")
                        .HasColumnType("text");

                    b.Property<int?>("FiscalYearId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("JobCompleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("JobDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("JobStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("JobStep")
                        .HasColumnType("integer");

                    b.Property<string>("JobStepId")
                        .HasColumnType("text");

                    b.Property<int>("JobTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("LotNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NoofAssociatedForma")
                        .HasColumnType("integer");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("PrePrintSize")
                        .HasColumnType("integer");

                    b.Property<int?>("PrintAchieved")
                        .HasColumnType("integer");

                    b.Property<int?>("PrintTarget")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FiscalYearId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("ProductId");

                    b.ToTable("JobTicket");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 45, 0, 0)),
                            Desc = "Description 1",
                            FiscalYearId = 1,
                            JobCompleteDate = new DateTimeOffset(new DateTime(2024, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 45, 0, 0)),
                            JobDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 45, 0, 0)),
                            JobStartDate = new DateTimeOffset(new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 45, 0, 0)),
                            JobStepId = "Step1",
                            JobTypeId = 1,
                            LotNumber = 100,
                            Name = "Job 1",
                            NoofAssociatedForma = 10,
                            PageNumber = 1,
                            PrePrintSize = 50,
                            PrintAchieved = 950,
                            PrintTarget = 1000,
                            ProductId = 1,
                            Remarks = "Remarks 1",
                            Status = true,
                            UpdatedBy = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 2,
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 45, 0, 0)),
                            Desc = "Description 2",
                            FiscalYearId = 2,
                            JobCompleteDate = new DateTimeOffset(new DateTime(2024, 1, 2, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 45, 0, 0)),
                            JobDate = new DateTimeOffset(new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 45, 0, 0)),
                            JobStartDate = new DateTimeOffset(new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 5, 45, 0, 0)),
                            JobStepId = "Step2",
                            JobTypeId = 1,
                            LotNumber = 101,
                            Name = "Job 2",
                            NoofAssociatedForma = 10,
                            PageNumber = 2,
                            PrePrintSize = 100,
                            PrintAchieved = 1900,
                            PrintTarget = 2000,
                            ProductId = 2,
                            Remarks = "Remarks 2",
                            Status = true,
                            UpdatedBy = 2
                        });
                });

            modelBuilder.Entity("Ecom.Models.JobType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JobType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pre-Press"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Press"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Post-Press"
                        });
                });

            modelBuilder.Entity("Ecom.Models.Machinary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("JobStep")
                        .HasColumnType("integer");

                    b.Property<string>("JobStepId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Machinary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oliver "
                        },
                        new
                        {
                            Id = 2,
                            Name = "RMGT"
                        },
                        new
                        {
                            Id = 3,
                            Name = "NaphA"
                        });
                });

            modelBuilder.Entity("Ecom.Models.MachineJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Desc")
                        .HasColumnType("text");

                    b.Property<int?>("FiscalYear")
                        .HasColumnType("integer");

                    b.Property<int>("FormaId")
                        .HasColumnType("integer");

                    b.Property<int?>("FormaPageSize")
                        .HasColumnType("integer");

                    b.Property<int?>("FormaTarget")
                        .HasColumnType("integer");

                    b.Property<int?>("InchargeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("JobDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("JobQuantity")
                        .HasColumnType("integer");

                    b.Property<int?>("JobStep")
                        .HasColumnType("integer");

                    b.Property<string>("JobStepId")
                        .HasColumnType("text");

                    b.Property<int>("JobTicketId")
                        .HasColumnType("integer");

                    b.Property<int?>("JobTicketTarget")
                        .HasColumnType("integer");

                    b.Property<int>("JobTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("MachinaryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReportDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Shift")
                        .HasColumnType("integer");

                    b.Property<int?>("ShiftDuration")
                        .HasColumnType("integer");

                    b.Property<string>("ShiftDurationId")
                        .HasColumnType("text");

                    b.Property<string>("ShiftId")
                        .HasColumnType("text");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FormaId");

                    b.HasIndex("JobTicketId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex("MachinaryId");

                    b.HasIndex("ProductId");

                    b.ToTable("MachineJobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = 1,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Description 1",
                            FormaId = 1,
                            FormaPageSize = 10,
                            InchargeId = 1,
                            JobDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobQuantity = 10,
                            JobStepId = "Step1",
                            JobTicketId = 1,
                            JobTypeId = 1,
                            MachinaryId = 1,
                            Name = "Machine Job 1",
                            ProductId = 1,
                            Remarks = "Remarks 1",
                            ReportDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftDurationId = "Duration1",
                            ShiftId = "Shift1",
                            Status = true,
                            SupervisorId = 1,
                            UpdatedBy = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = 2,
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Description 2",
                            FormaId = 2,
                            FormaPageSize = 10,
                            InchargeId = 2,
                            JobDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobQuantity = 10,
                            JobStepId = "Step2",
                            JobTicketId = 2,
                            JobTypeId = 2,
                            MachinaryId = 2,
                            Name = "Machine Job 2",
                            ProductId = 2,
                            Remarks = "Remarks 2",
                            ReportDate = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShiftDurationId = "Duration2",
                            ShiftId = "Shift2",
                            Status = true,
                            SupervisorId = 2,
                            UpdatedBy = 2
                        });
                });

            modelBuilder.Entity("Ecom.Models.P2M", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CheckedById")
                        .HasColumnType("integer");

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Desc")
                        .HasColumnType("text");

                    b.Property<int?>("DropdownVId")
                        .HasColumnType("integer");

                    b.Property<int?>("FiscalYear")
                        .HasColumnType("integer");

                    b.Property<int?>("FormaNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("JobStep")
                        .HasColumnType("integer");

                    b.Property<string>("JobStepId")
                        .HasColumnType("text");

                    b.Property<int?>("JobTicketId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("P2MDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("P2M_Code")
                        .HasColumnType("text");

                    b.Property<int?>("PerPokaSize")
                        .HasColumnType("integer");

                    b.Property<int?>("PiecesQuantity")
                        .HasColumnType("integer");

                    b.Property<int?>("PokaNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductQuantity")
                        .HasColumnType("integer");

                    b.Property<int?>("ReceivedById")
                        .HasColumnType("integer");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReportDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalProductQuantity")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("VerifiedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("DropdownVId");

                    b.HasIndex("JobTicketId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SubjectId");

                    b.ToTable("P2M");
                });

            modelBuilder.Entity("Ecom.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<double?>("BasePrice")
                        .HasColumnType("double precision");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClassId")
                        .HasColumnType("integer");

                    b.Property<double?>("CostPrice")
                        .HasColumnType("double precision");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("FiscalYear")
                        .HasColumnType("integer");

                    b.Property<int>("FormaNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ISBN")
                        .HasColumnType("text");

                    b.Property<string>("ImageURL")
                        .HasColumnType("text");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<bool?>("Status")
                        .HasColumnType("boolean");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectLanguageId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubjectLanguages")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubjectTypes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author 1",
                            BasePrice = 100.0,
                            CategoryId = 1,
                            ClassId = 1,
                            CostPrice = 50.0,
                            CreatedBy = "Admin",
                            Description = "Description 1",
                            FiscalYear = 2080,
                            FormaNumber = 0,
                            ISBN = "ISBN-1",
                            ImageURL = "http://example.com/product1.jpg",
                            PageNumber = 100,
                            Status = true,
                            SubjectId = 1,
                            SubjectLanguageId = 0,
                            SubjectTypeId = 1,
                            Title = "Product 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author 2",
                            BasePrice = 200.0,
                            CategoryId = 2,
                            ClassId = 2,
                            CostPrice = 150.0,
                            CreatedBy = "Admin",
                            Description = "Description 2",
                            FiscalYear = 2081,
                            FormaNumber = 0,
                            ISBN = "ISBN-2",
                            ImageURL = "http://example.com/product2.jpg",
                            PageNumber = 200,
                            Status = true,
                            SubjectId = 2,
                            SubjectLanguageId = 0,
                            SubjectTypeId = 1,
                            Title = "Product 2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author 1",
                            BasePrice = 100.0,
                            CategoryId = 1,
                            ClassId = 1,
                            CostPrice = 50.0,
                            CreatedBy = "Admin",
                            Description = "Description 1",
                            FiscalYear = 2080,
                            FormaNumber = 0,
                            ISBN = "ISBN-1",
                            ImageURL = "http://example.com/product1.jpg",
                            PageNumber = 100,
                            Status = true,
                            SubjectId = 1,
                            SubjectLanguageId = 0,
                            SubjectTypeId = 1,
                            Title = "Product 3"
                        });
                });

            modelBuilder.Entity("Ecom.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<bool?>("status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Math"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nepali"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ecom.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeID")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("dob")
                        .HasColumnType("timestamp without time zone");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Ecom.Models.Forma", b =>
                {
                    b.HasOne("Ecom.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecom.Models.JobTicket", b =>
                {
                    b.HasOne("Ecom.Models.FiscalYear", "FiscalYear")
                        .WithMany()
                        .HasForeignKey("FiscalYearId");

                    b.HasOne("Ecom.Models.JobType", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecom.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FiscalYear");

                    b.Navigation("JobType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecom.Models.MachineJob", b =>
                {
                    b.HasOne("Ecom.Models.Forma", "Forma")
                        .WithMany()
                        .HasForeignKey("FormaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ecom.Models.JobTicket", "JobTicket")
                        .WithMany()
                        .HasForeignKey("JobTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecom.Models.JobType", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ecom.Models.Machinary", "Machinary")
                        .WithMany()
                        .HasForeignKey("MachinaryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Ecom.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Forma");

                    b.Navigation("JobTicket");

                    b.Navigation("JobType");

                    b.Navigation("Machinary");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecom.Models.P2M", b =>
                {
                    b.HasOne("Ecom.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecom.Models.DropdownV", "DropdownV")
                        .WithMany()
                        .HasForeignKey("DropdownVId");

                    b.HasOne("Ecom.Models.JobTicket", "JobTicket")
                        .WithMany()
                        .HasForeignKey("JobTicketId");

                    b.HasOne("Ecom.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("Ecom.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.Navigation("Class");

                    b.Navigation("DropdownV");

                    b.Navigation("JobTicket");

                    b.Navigation("Product");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Ecom.Models.Product", b =>
                {
                    b.HasOne("Ecom.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ecom.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ecom.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Class");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
